### ISSUE TITLE
Incompatible Content-Type with XML body

### ISSUE THREAD

**Issue by orcolin** [realexpayments/rxp-remote-php#13]
I have got following error while sending request using RealexClient:
Content-Type header invalid or not present. Please set the Content-Type header to "application/xml" or "text/xml".

Changing code in HttpClient.php from
curl_setopt( $ch, CURLOPT_HTTPHEADER, array( 'Content-Type: text/plain' ) );
to
"curl_setopt( $ch, CURLOPT_HTTPHEADER, array( 'Content-Type: application/xml' ) );"
solve the problem for me, could you update the package or how it is validated on server ends.

**Comment by RealexITSO** [comment]
This has been resolved in the latest release.
