### ISSUE TITLE
Charging client using realvault without DCC

### ISSUE THREAD

**Issue by kingio** [realexpayments/rxp-remote-php#16]
I want to charge a client using it's stored card, which type is it?
I've only found "STORED_CARD_DCC_RATE" containing "stored_card" reference, but that also requires DCC service which i dont want.
```php

        $request = (new PaymentRequest())
            ->addMerchantId("????")
            ->addAccount("internet")
            ->addType(PaymentType::STORED_CARD_DCC_RATE)
            ->addAmount($amount * 100)
            ->addCurrency("EUR")
            ->addPayerReference($this->uid)
            ->addPaymentMethod($this->getCardReference());

        $response = $this->realexClient()->send($request);
        p($response->getResult(),  $response->getMessage());
        exit;
```

**Comment by rxp-developers** [comment]
Hi @kingio, please see Step 3 of the following guide; https://developer.realexpayments.com/#!/integration-api/card-storage/php/html_js

The request type is known as a receipt-in.

**Comment by kingio** [comment]
TY!
