### ISSUE TITLE
More SDK examples?

### ISSUE THREAD

**Issue by cscd98** [realexpayments/rxp-remote-php#2]
For example, it doesn't tell you how to:

Change the location of the config.xml which is used to specify logging?
How to deal with responses from realex?
It doesn't tell you how to do refunds?

**Comment by seanmacdomhnall** [comment]
Hi Craig,

Thanks for the feedback.

The SDK uses log4php for logging, please see the quick start guide: https://logging.apache.org/log4php/quickstart.html

The SDK currently doesn't support rebates or refunds but these enhancements will be coming shortly.

As for examples on how to handle the response, we'll update these on the Developer Hub: https://developer.realexpayments.com/. As soon as you have the response object you can use the getter methods available in the PaymentResponse class:

https://github.com/realexpayments/rxp-remote-php/blob/master/src/main/php/com-realexpayments-remote-sdk/domain/payment/PaymentResponse.php

Best,

Seán

**Comment by cscd98** [comment]
@seanmacdomhnall Hi Sean, what happened to the enhancements? I still need rebates, refunds, 3d Secure, storing of tokens

**Comment by seanmacdomhnall** [comment]
@craigcarnell,

3D Secure is available in the SDK already (just not for tokens). Rebates, refunds and Card Storage (including 3D Secure) calls are 99% QA'd and available here:

https://github.com/realexpayments-developers/rxp-remote-php/

We'll be creating a pull request to the main repo in about a week or so. The new functionality will also be fully documented on https://developer.realexpayments.com

Best,

Seán

**Comment by cscd98** [comment]
@seanmacdomhnall Thank you.

**Comment by cscd98** [comment]
@seanmacdomhnall Hi Sean, Where is this PR? Thank you
