### ISSUE TITLE
3dsecure v2?

### ISSUE THREAD

**Issue by cscd98** [realexpayments/rxp-remote-php#31]
https://developer.realexpayments.com/#!/api/3d-secure-two

**Comment by rxp-developers** [comment]
Hi Craig,

As per your other question, 3D Secure 2 functionality will be developed in https://github.com/globalpayments/php-sdk

**Comment by cscd98** [comment]
@rxp-developers Does that mean this API is no longer being developed?

**Comment by rxp-developers** [comment]
@craigcarnell we'll continue to support this SDK, however, any new features will only be developed on https://github.com/globalpayments/php-sdk
