### ISSUE TITLE
Strong Customer Authentication (SCA)

### ISSUE THREAD

**Issue by cscd98** [realexpayments/rxp-remote-php#33]
Recieved this email:

```
To support the Strong Customer Authentication (SCA) requirement that's due to go live in September 2019, we'll be making a change to the messaging we return in some of our card transaction responses.
```

Does the API need any modification to keep working post this date please??

**Comment by rxp-developers** [comment]
Hi Craig,

3D Secure 2 functionality will not be added to this SDK, it will be added to
https://github.com/globalpayments/php-sdk
