### ISSUE TITLE
V1.1 won't work because Content-type is not text/xml or application/xml

### ISSUE THREAD

**Issue by w-sanches** [realexpayments/rxp-remote-php#4]
After installing the SDK through composer, I had to edit com-realexpayments-remote-sdk/http/HttpClient.php because it sets Content-type to text/plain and the API throws an error saying it must be text/xml or application/xml.

**Comment by seanmacdomhnall** [comment]
Hi,

Thanks for getting in touch. Could you please send us on:
- OS and version you're using.
- PHP version you're using.
- What code exactly were you executing when you encountered this error.
- What was the exact error message you got.

We have other merchants / developers using the SDK so it doesn't appear to be a generic issue but if you could provide this information we can investigate further.

Seán MacDomhnall
**Realex Payments**

**Comment by w-sanches** [comment]
Ubuntu 14.04
PHP 5.5.9
The exact same code that is written as an example in this project's readme.
The error message is:
Content-Type header invalid or not present. Please set the Content-Type header to "application/xml" or text/xml"

**Comment by seanmacdomhnall** [comment]
Hi,

We've been unable to replicate this issue. Can you please advise what version of Apache you are using?

For the next release of the SDK we've changed this in any case as it's best practice:
https://github.com/realexpayments-developers/rxp-remote-php/blob/master/src/main/php/com-realexpayments-remote-sdk/http/HttpClient.php#L57

(realexpayments-developers is where we work on the SDKs before formally releasing them.)

Seán MacDomhnall
**Realex Payments**

**Comment by w-sanches** [comment]
I am using latest Apache version (2.4, IIRC).
Well, good thing it will not be a problem later.
