### ISSUE TITLE
How to generate refund hash for rebate?

### ISSUE THREAD

**Issue by cscd98** [realexpayments/rxp-remote-php#6]
You can set it, get it.. but how to generate?

**Comment by seanmacdomhnall** [comment]
Hi Craig,

The refund hash is created by hashing the Refund or Rebate Password (depending on the request you wish to process). So for example in PHP:

`$refundHash = sha1("Refund Password");`

You then add that variable to your request object.

Best,

Seán

**Comment by cscd98** [comment]
Thanks
